name: ucu
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - absl-py=0.9.0
  - astor=0.8.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - blinker=1.4
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - colorama=0.4.3
  - cryptography=2.9.2
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - gast=0.2.2
  - google-auth=1.14.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.9
  - importlib_metadata=1.5.0
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libsodium=1.0.16
  - libtiff=4.1.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - protobuf=3.11.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.4.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard=2.1.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cloudpickle==1.4.1
    - future==0.18.2
    - gpy==1.9.8
    - gpyopt==1.2.1
    - hyperopt==0.2.4
    - networkx==2.4
    - paramz==0.9.5
    - scikit-optimize==0.5.2
    - tqdm==4.46.0
    - xgboost==0.90
prefix: C:\Users\HP\Anaconda3\envs\ucu

